### ISSUE TITLE
[bug] [WhoReacted]  Cannot read property 'default' of undefined on Discord startup 

### ISSUE THREAD

**Issue by kekonn** [jaimeadf/BetterDiscordPlugins#364] opened 2022-09-23 15:28 UTC
Since a couple of days ago, WhoReacted isn't working. Upon starting discord, I get the following error:

```
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:166:124)
    at buildPlugin (betterdiscord://plugins/WhoReacted.plugin.js:434:12)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:441:7)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at FSWatcher.<anonymous> (<anonymous>:4:7059)
```

## Discord data
```
Stable 148479 (5a3ca25)
BetterDiscord 1.6.3
Host 0.0.20 Linux 64-Bit (5.19.8-1-Default)
```

I have the flatpak version. Other plugins are working fine.

**Comment by jaimeadf** [comment] 2022-09-23 18:08
Are you using the version 1.2.7 of WhoReacted?

**Comment by kekonn** [comment] 2022-09-23 18:37
The latest version available through either betterdiscord.app or the Plugin Repo is 1.2.5. I just downloaded both to compare.

**Comment by jaimeadf** [comment] 2022-09-23 19:55
The website and plugin repo only update after the new version has been approved by a BD moderator. If you want the latest version, download the file `dist/WhoReacted.plugin.js` from GitHub.

**Comment by marcpinet** [comment] 2022-09-25 11:00
> The website and plugin repo only update after the new version has been approved by a BD moderator. If you want the latest version, download the file `dist/WhoReacted.plugin.js` from GitHub.

TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:166:124)
    at buildPlugin (betterdiscord://plugins/WhoReacted.plugin.js:434:12)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:441:7)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at FSWatcher.<anonymous> (<anonymous>:4:7059)

It happens with your latest version too.

**Comment by jeanmichelmorin** [comment] 2022-09-25 20:54
Can confirm. It seems to work fine at my work computer, but not on my home computer. Updates were made on both computers... It's odd.

The "1.2.7" version on your github is still 1.2.5. At least it's what's written in the `.js` file.

**Comment by jaimeadf** [comment] 2022-09-25 22:49
The download badge in the README is just a redirect to the website. You have to go the file and click `view raw` then `save as` to get the latest version.

**Comment by marcpinet** [comment] 2022-09-25 22:58
> The download badge in the README is just a redirect to the website. You must go to the file, click `view raw`, and then `save as` to get the latest version.

Still the same issue.

**Comment by jeanmichelmorin** [comment] 2022-09-25 23:31
> The download badge in the README is just a redirect to the website. You must go to the file, click `view raw`, and then `save as` to get the latest version.

This has worked, thank you. 

@kekonn @marcpinet refer to this solution.

**Comment by 0rangeAppl3** [comment] 2022-10-03 11:05
I download the latest js from the link above and the issues still remain. Any ideas how to solve it? Thanks

**Comment by jeanmichelmorin** [comment] 2022-10-03 11:20
> I download the latest js from the link above and the issues still remain. Any ideas how to solve it? Thanks

BetterDiscord issued a statement mentioning that Discord updated a lot of internal modules of Discord by changing the structure of code, thus broke a lot of BetterDiscord plugins. They will have to update BetterDiscord as well to accomodate these changes, and the plugins devs as well. But there's currently no ETA on when it will be fixed.

**Comment by HypdUp** [comment] 2022-10-12 11:50
broken again

**Comment by CallMeTerdFerguson** [comment] 2022-11-06 17:43
@jaimeadf or any other contributors, any update on if there will be a fix issued for the latest set of discord/betterdiscord updates and if so when you might find time? This is the last one of my plugins that hasn't been updated for the changes yet and it's by far one of my favorite plugins, really missing it. I wish I had stronger JS skills so I could contribute a PR but not confident enough.

**Comment by merri1400** [comment] 2022-11-06 20:23
I believe they said in the Discord in September they would not have time to do it this year

**Comment by FichteFoll** [comment] 2022-11-06 21:49
I have contributed before, but my knowledge of React and especially how to interact with it from BetterDiscord plugins is basically zero, so I don't have any hands in this. I'm also of course still interested in a fix since hovering over reactions to see who made them again is really getting on my nerves.

**Comment by KenLHua** [comment] 2023-01-25 04:28
Seems the issue is related to 

`const { Reaction } = WebpackModules.getByProps('Reaction');`

and

`const VoiceUserSummaryItem = WebpackModules.find(m => m?.default?.displayName === 'VoiceUserSummaryItem').default;`

are undefined values. 


These components probably either got renamed or refactored in some way. I couldn't figure out what they were renamed to. GL to whoever looks at it after.

Maybe searching for the module using `WebpackModules.getByDisplayName('VoiceUserSummaryItem')` could help?

**Comment by KaKi87** [comment] 2023-02-28 17:12
Hello,
Any news on this ?
Thanks

**Comment by jaimeadf** [comment] 2023-03-31 23:13
It's finally fixed. Here's the [download link](https://git-link.vercel.app/api/download?url=https://github.com/jaimeadf/BetterDiscordPlugins/blob/build/WhoReacted/dist/WhoReacted.plugin.js).

**Closed by jaimeadf** 2023-03-31 23:13 UTC
